# This is a basic workflow to help you get started with Actions
name: PlatformIO CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  platformio-build:
    runs-on: ubuntu-latest
    container: infinitecoding/platformio-for-ci:latest

    steps:
      - uses: actions/checkout@v4

      - name: Upgrade PlatformIO
        run: pio upgrade

      - name: Check PlatformIO version
        run: pio --version

      - name: Install ESP32 platform
        run: pio platform install espressif32

      - name: Build firmware ESP32
        run: pio run -d .

      - name: Upload firware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware.elf
          path: example/.pio/build/esp12e/firmware.elf
